import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display } from "next/font/google";
import Navbar from "./components/ui/Navbar";

const playfairdisplay = Playfair_Display({
  variable: "--font-playfairdisplay",
  subsets: ["cyrillic"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfairdisplay.variable} antialiased`}>
        <Navbar /> 
        <div className="px-[35px]">{children}</div>
      </body>
    </html>
  );
}
